#ifndef __FLOATARRAY_H
#define __FLOATARRAY_H

float* array_addf(float * x, float * y, int M, int N, int O, int P);
float* array_subf(float * x, float * y, int M, int N, int O, int P);
float* array_mulf(float * x, float * y, int M, int N, int O, int P);
float* array_divf(float * x, float * y, int M, int N, int O, int P);
float* array_modf(float * x, float * y, int M, int N, int O, int P);
float* array_acosf(float * x, int M, int N, int O, int P);
float* array_asinf(float * x, int M, int N, int O, int P);
float* array_atanf(float * x, int M, int N, int O, int P);
float* array_atan2f(float * a, float * b, int M, int N, int O, int P);
float* array_acoshf(float * x, int M, int N, int O, int P);
float* array_asinhf(float * x, int M, int N, int O, int P);
float* array_atanhf(float * x, int M, int N, int O, int P);
float* array_cosf(float * x, int M, int N, int O, int P);
float* array_sinf(float * x, int M, int N, int O, int P);
float* array_tanf(float * x, int M, int N, int O, int P);
float* array_coshf(float * x, int M, int N, int O, int P);
float* array_sinhf(float * x, int M, int N, int O, int P);
float* array_tanhf(float * x, int M, int N, int O, int P);
float* array_ceilf(float * x, int M, int N, int O, int P);
float* array_exp10f(float * x, int M, int N, int O, int P);
float* array_exp2f(float * x, int M, int N, int O, int P);
float* array_expf(float * x, int M, int N, int O, int P);
float* array_expm1f(float * x, int M, int N, int O, int P);
float* array_fabsf(float * x, int M, int N, int O, int P);
float* array_floorf(float * x, int M, int N, int O, int P);
float* array_fmaxf(float * x, float * y, int M, int N, int O, int P);
float* array_fminf(float * x, float * y, int M, int N, int O, int P);
float* array_fmodf(float * x, float * y, int M, int N, int O, int P);
float* array_log10f(float * x, int M, int N, int O, int P);
float* array_log1pf(float * x, int M, int N, int O, int P);
float* array_log2f(float * x, int M, int N, int O, int P);
float* array_logbf(float * x, int M, int N, int O, int P);
float* array_powf(float * x, float * y, int M, int N, int O, int P);
float* array_rsqrtf(float * x, int M, int N, int O, int P);
float* array_sinf(float * x, int M, int N, int O, int P);
float* array_sinhf(float * x, int M, int N, int O, int P);
float* array_sinpif(float * x, int M, int N, int O, int P);
float* array_sqrtf(float * x, int M, int N, int O, int P);
float* array_tanf(float * x, int M, int N, int O, int P);
float* array_tanhf(float * x, int M, int N, int O, int P);
float* array_softmaxf(float * x, int M, int N, int O, int P);
float* array_sigmoidf(float * x, int M, int N, int O, int P);
float* array_sigmoid_gradf(float * x, int M, int N, int O, int P);
float* array_tanh_gradf(float * x, int M, int N, int O, int P);
float* array_reluf(float * x, int M, int N, int O, int P);
float* array_relu_gradf(float * x, int M, int N, int O, int P);

float* array_cbrtf(float * x, int M, int N, int O, int P);
float* array_cospif(float * x, int M, int N, int O, int P);
float* array_cyl_bessel_i0f(float * x, int M, int N, int O, int P);
float* array_cyl_bessel_i1f(float * x, int M, int N, int O, int P);
float* array_erfcf(float * x, int M, int N, int O, int P);
float* array_erfcinvf(float * x, int M, int N, int O, int P);
float* array_erfcxf(float * x, int M, int N, int O, int P);
float* array_erff(float * x, int M, int N, int O, int P);
float* array_erfinvf(float * x, int M, int N, int O, int P);
float* array_fdimf(float * a, float * b, int M, int N, int O, int P);
float* array_fdividef(float * a, float * b, int M, int N, int O, int P);
float* array_fmaf(float * x, float * y, float * z, int M, int N, int O, int P);
float* array_hypotf(float * x, float * y, int M, int N, int O, int P);
float* array_ilogbf(float * x, int M, int N, int O, int P);
float* array_j0f(float * x, int M, int N, int O, int P);
float* array_j1f(float * x, int M, int N, int O, int P);
float* array_jnf(float * x, int _M, int M,int N, int O,int P);
float* array_ldexpf(float * x,int exp, int M, int N, int O, int P);
float* array_lgammaf(float * x, int M, int N, int O, int P);
float* array_nearbyintf(float * x, int M, int N, int O, int P);
float* array_norm3df(float * x, float * y, float * z, int M, int N, int O, int P);
float* array_norm4df(float * x, float * y, float * z, float * q, int M, int N, int O, int P);
float* array_normcdff(float * x, int M, int N, int O, int P);
float* array_normcdfinvf(float * x, int M, int N, int O, int P);
float* array_normf(int dim, float * x, int M, int N, int O, int P);
float* array_rcbrtf(float * x, int M, int N, int O, int P);
float* array_remainderf(float * x, float * y, int M, int N, int O, int P);
float* array_rhypotf(float * x, float * y, int M, int N, int O, int P);
float* array_rnorm3df(float * x, float * y, float * z, int M, int N, int O, int P);
float* array_rnorm4df(float * x, float * y, float * z, float * q, int M, int N, int O, int P);
float* array_rnormf(int dim, float * x, int M, int N, int O, int P);
float* array_scalblnf(float * x, long int _M, int M, int N, int O, int P);
float* array_tgammaf(float * x, int M, int N, int O, int P);
float* array_truncf(float * x, int M, int N, int O, int P);
float* array_y0f(float * x, int M, int N, int O, int P);
float* array_y1f(float * x, int M, int N, int O, int P);
float* array_ynf(int _M, float * x, int M, int N, int O, int P);
float* array_copysignf(float * X, float *Y, int M, int N, int O, int P);
float* array_cospif(float * x, int M, int N, int O, int P);
float* array_cyl_bessel_i0f(float * x, int M, int N, int O, int P);
float* array_cyl_bessel_i1f(float * x, int M, int N, int O, int P);
float* array_erfcf(float * x, int M, int N, int O, int P);
float* array_erfcinvf(float * x, int M, int N, int O, int P);
float* array_erfcxf(float * x, int M, int N, int O, int P);
float* array_erff(float * x, int M, int N, int O, int P);
float* array_erfinvf(float * x, int M, int N, int O, int P);
float* array_fdimf(float * x, float * y, int M, int N, int O, int P);
float* array_fdividef(float * x, float * y, int M, int N, int O, int P);
float* array_fmaf(float * x, float * y, float * z, int M, int N, int O, int P);
float* array_hypotf(float * x, float * y, int M, int N, int O, int P);
float* array_ilogbf(float * x, int M, int N, int O, int P);
float* array_j0f(float * x, int M, int N, int O, int P);
float* array_j1f(float * x, int M, int N, int O, int P);
float* array_jnf(float * x, int m, int M, int N, int O, int P);
float* array_ldexpf(float * x,int exp, int M, int N, int O, int P);
float* array_lgammaf(float * x, int M, int N, int O, int P);
float* array_nearbyintf(float * x, int M, int N, int O, int P);
float* array_norm3df(float * x, float * y, float * z, int M, int N, int O, int P);
float* array_norm4df(float * x, float * y, float * z, float * q, int M, int N, int O, int P);
float* array_normcdff(float * x, int M, int N, int O, int P);
float* array_normf(int dim, float * x, int M, int N, int O, int P);
float* array_rnorm3df(float * x, float * y, float * z, int M, int N, int O, int P);
float* array_rnorm4df(float * x, float * y, float * z, float * q, int M, int N, int O, int P);
float* array_rnormf(int dim, float * x, int M, int N, int O, int P);
float* array_rcbrtf(float * x, int M, int N, int O, int P);
float* array_rhypotf(float * x, float * y, int M, int N, int O, int P);
float* array_scalblnf(float * x, long int _M, int M, int N, int O, int P);
float* array_sinpif(float * x, int M, int N, int O, int P);
float* array_tgammaf(float * x, int M, int N, int O, int P);
float* array_truncf(float * x, int M, int N, int O, int P);
float* array_y0f(float * x, int M, int N, int O, int P);
float* array_y1f(float * x, int M, int N, int O, int P);
float* array_ynf(int m,float * x, int M, int N, int O, int P);



void array_r_addf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_subf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_mulf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_divf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_modf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_acosf(float * x, float * output,int M, int N, int O, int P);
void array_r_asinf(float * x, float * output,int M, int N, int O, int P);
void array_r_atanf(float * x, float * output,int M, int N, int O, int P);
void array_r_atan2f(float * a, float * b, float * output,int M, int N, int O, int P);
void array_r_acoshf(float * x, float * output,int M, int N, int O, int P);
void array_r_asinhf(float * x, float * output,int M, int N, int O, int P);
void array_r_atanhf(float * x, float * output,int M, int N, int O, int P);
void array_r_cosf(float * x, float * output,int M, int N, int O, int P);
void array_r_sinf(float * x, float * output,int M, int N, int O, int P);
void array_r_tanf(float * x, float * output,int M, int N, int O, int P);
void array_r_coshf(float * x, float * output,int M, int N, int O, int P);
void array_r_sinhf(float * x, float * output,int M, int N, int O, int P);
void array_r_tanhf(float * x, float * output,int M, int N, int O, int P);
void array_r_acosf(float * x, float * output,int M, int N, int O, int P);
void array_r_asinf(float * x, float * output,int M, int N, int O, int P);
void array_r_ceilf(float * x, float * output, int M, int N, int O, int P);
void array_r_exp10f(float * x, float * output, int M, int N, int O, int P);
void array_r_exp2f(float * x, float * output, int M, int N, int O, int P);
void array_r_expf(float * x, float * output, int M, int N, int O, int P);
void array_r_expm1f(float * x, float * output, int M, int N, int O, int P);
void array_r_fabsf(float * x, float * output,  int M, int N, int O, int P);
void array_r_floorf(float * x, float *output, int M, int N, int O, int P);
void array_r_fmaxf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_fminf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_fmodf(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_log10f(float * x,float *output, int M, int N, int O, int P);
void array_r_log1pf(float * x, float *output, int M, int N, int O, int P);
void array_r_log2f(float * x, float *output, int M, int N, int O, int P);
void array_r_logbf(float * x, float * output, int M, int N, int O, int P);
void array_r_powf(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_rsqrtf(float * x, float *output, int M, int N, int O, int P);
void array_r_sqrtf(float * x, float * output, int M, int N, int O, int P);
void array_r_softmaxf(float * x, float *output, int M, int N, int O, int P);
void array_r_sigmoidf(float * x, float *output, int M, int N, int O, int P);
void array_r_sigmoid_gradf(float * x, float * output, int M, int N, int O, int P);
void array_r_tanh_gradf(float * x, float *output, int M, int N, int O, int P);
void array_r_reluf(float * x, float *output, int M, int N, int O, int P);
void array_r_relu_gradf(float * x, float *output, int M, int N, int O, int P);


void array_r_cbrtf(float * x, float * output, int M, int N, int O, int P);
void array_r_cospif(float * x, float * output, int M, int N, int O, int P);
void array_r_cyl_bessel_i0f(float * x, float * output, int M, int N, int O, int P);
void array_r_cyl_bessel_i1f(float * x, float * output, int M, int N, int O, int P);
void array_r_erfcf(float * x, float * output, int M, int N, int O, int P);
void array_r_erfcinvf(float * x, float * output, int M, int N, int O, int P);
void array_r_erfcxf(float * x, float * output, int M, int N, int O, int P);
void array_r_erff(float * x, float * output, int M, int N, int O, int P);
void array_r_erfinvf(float * x, float * output, int M, int N, int O, int P);
void array_r_fdimf(float * a, float * b, float * output, int M, int N, int O, int P);
void array_r_fdividef(float * a, float * b, float * output, int M, int N, int O, int P);
void array_r_fmaf(float * x, float * y, float * z, float *output, int M, int N, int O, int P);
void array_r_hypotf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_ilogbf(float * x, float * output, int M, int N, int O, int P);
void array_r_j0f(float * x, float *output, int M, int N, int O, int P);
void array_r_j1f(float * x, float *output, int M, int N, int O, int P);
void array_r_jnf(float * x, float * output, int _M, int M,int N, int O,int P);
void array_r_ldexpf(float * x, float * output, int exp, int M, int N, int O, int P);
void array_r_lgammaf(float * x, float *output, int M, int N, int O, int P);
void array_r_nearbyintf(float * x, float *output, int M, int N, int O, int P);
void array_r_norm3df(float * x, float * y, float * z, float *output, int M, int N, int O, int P);
void array_r_norm4df(float * x, float * y, float * z, float * q, float * output, int M, int N, int O, int P);
void array_r_normcdff(float * x, float * output, int M, int N, int O, int P);
void array_r_normcdfinvf(float * x, float *output, int M, int N, int O, int P);
void array_r_normf(int dim, float * x, float * output, int M, int N, int O, int P);
void array_r_rcbrtf(float * x, float *output, int M, int N, int O, int P);
void array_r_remainderf(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_rhypotf(float * x, float * y, float * output, int M, int N, int O, int P);
void array_r_rnorm3df(float * x, float * y, float * z, float * output, int M, int N, int O, int P);
void array_r_rnorm4df(float * x, float * y, float * z, float * q, float *output,int M, int N, int O, int P);
void array_r_rnormf(int dim, float * x, float *output, int M, int N, int O, int P);
void array_r_scalblnf(float * x, long int _M, float * output, int M, int N, int O, int P);
void array_r_tgammaf(float * x, float *output, int M, int N, int O, int P);
void array_r_truncf(float * x, float *output, int M, int N, int O, int P);
void array_r_y0f(float * x, float *output, int M, int N, int O, int P);
void array_r_y1f(float * x, float * output, int M, int N, int O, int P);
void array_r_ynf(int _M, float * x, float *output, int M, int N, int O, int P);
void array_r_sinpif(float * x, float *output, int M, int N, int O, int P);
void array_r_fdimf_const(float * a, float  b, float *output, int M, int N, int O, int P);
void array_r_fdividef_const(float * a, float b, float * p, float *output, int M, int N, int O, int P);
void array_r_hypotf_const(float * x, float y, float *p, float *output, int M, int N, int O, int P);
void array_r_remainderf_const(float * x, float y, float *p, float *output,int M, int N, int O, int P);
void array_r_hypotf_const(float * x, float y, float *p, float *output,int M, int N, int O, int P);
void array_r_copysignf(float * X, float *Y, float *output, int M, int N, int O, int P);
void array_r_cospif(float * x, float * output, int M, int N, int O, int P);
void array_r_cyl_bessel_i0f(float * x, float * output, int M, int N, int O, int P);
void array_r_cyl_bessel_i0f(float * x, float * output, int M, int N, int O, int P);


float* array_addf_const(float * x, float y, int M, int N, int O, int P);
float* array_subf_const(float * x, float y, int M, int N, int O, int P);
float* array_mulf_const(float * x, float y, int M, int N, int O, int P);
float* array_divf_const(float * x, float y, int M, int O, int N, int P);
float* array_modf_const(float * x, float y, int M, int N, int O, int P);
float* array_fmodf_const(float * x, float y, int M, int N, int O, int P);
float* array_fmaxf_const(float * x, float y, int M, int N, int O, int P);
float* array_fminf_const(float * x, float y, int M, int N, int O, int P);
float* array_powf_const(float * x, float y, int M, int N, int O, int P);
float* array_atan2f_const(float * x, float b, int M, int N, int O, int P);
float* array_fdimf_const(float * x, float  y, int M, int N, int O, int P);
float* array_fdividef_const(float * a, float b, int M, int N, int O, int P);
float* array_remainderf_const(float * x, float y, int M, int N, int O, int P);
float* array_rhypotf_const(float * x, float y, int M, int N, int O, int P);
float* array_hypotf_const(float * x, float y, int M, int N, int O, int P);


float* array_addf_scalar(float * x, float * y, int M, int N, int O, int P);
float* array_subf_scalar(float * x, float * y, int M, int N, int O, int P);
float* array_mulf_scalar(float * x, float * y, int M, int N, int O, int P);
float* array_divf_scalar(float * x, float * y, int M, int N, int O, int P);
float* array_modf_scalar(float * x, float * y, int M, int N, int O, int P);
float* array_fmaxf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_fminf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_powf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_hypotf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_rhypotf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_fdividef_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_fdimf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_remainderf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_fmodf_scalar(float * x, float *y, int M, int N, int O, int P);
float* array_atan2f_scalar(float * x, float *y, int M, int N, int O, int P);

void array_r_addf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_subf_const(float * x, float y, float *output,  int M, int N, int O, int P);
void array_r_mulf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_divf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_modf_const(float * x, float y, float * output, int M, int N, int O, int P);
void array_r_fmaxf_const(float * x, float y, float *p, int M, int N, int O, int P);
void array_r_fminf_const(float * x, float y, float *p, int M, int N, int O, int P);
void array_r_powf_const(float * x, float y, float *p, int M, int N, int O, int P);
void array_r_hypotf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_rhypotf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_fdividef_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_fdimf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_remainderf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_fmodf_const(float * x, float y, float *output, int M, int N, int O, int P);
void array_r_atan2f_const(float * x, float b, float * output, int M, int N, int O, int P);

void array_r_addf_scalar(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_subf_scalar(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_mulf_scalar(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_divf_scalar(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_modf_scalar(float * x, float * y, float *output, int M, int N, int O, int P);
void array_r_fmaxf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_fminf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_powf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_hypotf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_rhypotf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_fdividef_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_fdimf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_remainderf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_fmodf_scalar(float * x, float *y, float *output, int M, int N, int O, int P);
void array_r_atan2f_scalar(float * a, float *b, float * output, int M, int N, int O, int P);




#endif