name: build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq python3-pip libfftw3-dev ninja-build libsndfile1-dev
          sudo pip install meson
      - name: Build library
        shell: bash
        run: |
          meson build --buildtype release
          meson compile -v -C build